apiVersion: argoproj.io/v1alpha1
kind: Rollout # Rollout으로 생성
metadata:
  name: canary-with-blue-green-rollout
spec:
  replicas: 4
  #revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary
      demo: canary-with-blue-green
  template:
    metadata:
      labels:
        app: canary
        demo: canary-with-blue-green
    spec:
      containers:
      - name: canary-rollouts-demo
        image: particule/simplecolorapi:1.0 # 1.0 = red , 2.0 = blue, 3.0 = black
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
  # 이 부분에서 카나리로 지정
  strategy:
    canary:
      maxSurge: "25%"    # 마지막 setWeight 이후 최대 Rollout 될 pod 비율 정의
      maxUnavailable: 0  # 업데이트 될 때 사용할 수 없는 pod의 최대 수
      canaryService: canary-with-blue-green-service
      stableService: stable-with-blue-green-service
      trafficRouting:
        alb:
          ingress: canary-with-blue-green-ingress # fill a ingress name out
          # Reference to a Service that the Ingress must target in one of the rules (optional).
          # If omitted, uses canary.stableService.
          rootService: root-with-blue-green-service
          # Service port is the port which the Service listens on (required).
          servicePort: 80
          # stick session이 필요한 경우
          # stickinessConfig:
          #   enabled: true
          #   durationSeconds: 3600

      # Canarry의 Traffic 비율 조정을 이용하여 Blue/Green과 같이 사용
      steps:
      - setCanaryScale:
          replicas: 4 # spec.replicas와 동일한 비율로 기입
      - setWeight: 10
      - pause: { duration: 1m } 
      - setWeight: 30
      - pause: { duration: 1m } 
      - setWeight: 70
      - pause: {}