apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-canary-test
spec:
  destination:
    name: '' # name과 server는 동시에 사용 불가능
    namespace: rollout-canary-test
    server: >-
      https://D98A689AE1B38EBE81042D57E31C9785.sk1.ap-northeast-2.eks.amazonaws.com
  source:
    path: charts/Argocd/Rollout/canary/basic
    repoURL: 'https://github.com/seodea/helm-subchart.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
