kind: Service
apiVersion: v1
metadata:
  name: canary-service
spec:
  selector:
    app: canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30081
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-ing
  labels:
    env: dev
    app: A
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    #alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-01925fe3fdb467412,subnet-0183b83ada5e17406
    alb.ingress.kubernetes.io/security-groups: sg-05da8f99ad01efcdb
    kubernetes.io/ingress.class: alb
spec:
  #ingressClassName: alb
  rules:
    - host: 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
                service: 
                  name: canary-service
                  port:
                    number: 80
          - path: /A-dev-site
            pathType: Exact
            backend:
                service: 
                  name: canary-service
                  port:
                    number: 80